config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  scope module: :v1 do
    get :sign_up, to: 'users#new'
    post :sign_up, to: 'users#create'
    get :sign_in, to: 'sessions#new'
    post :sign_in, to: 'sessions#create'
    get :profile, to: 'users#show'
    get 'profile/edit', to: 'users#edit'
    patch 'profile/update', to: 'users#update'
    get 'profile/edit_password', to: 'users#edit_password'
    patch 'profile/update_password', to: 'users#update_password'
    delete :logout, to: 'sessions#destroy'
    resources :groups do
      resources :expenses, only: %i[create new] #do
      #     get :new
      #     post :new, to: 'groups#create'
      # end
    end
    post 'groups/new', to: 'groups#create'
    resources :friends, only: %i[index show new add destroy]
    post 'friends/add', to: 'friends#add'
  end

  root to: 'status#check'
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  PASSWORD_FORMAT = /\A
    (?=.*\d)           # Must contain a digit
    (?=.*[a-z])        # Must contain a lower case character
    (?=.*[A-Z])        # Must contain an upper case character
  /x
  has_secure_password
  has_many :own_groups, class_name: 'Group', foreign_key: :owner_id, inverse_of: :owner
  has_many :expenses, as: :expenseable
  has_and_belongs_to_many :groups,-> { distinct }, inverse_of: :members, uniq: true
  has_and_belongs_to_many :friends,class_name: "User", join_table: :friendships,
                          foreign_key: :user_id, association_foreign_key: :friend_user_id

  validates :full_name, presence: true
  validates :password, format: { with: PASSWORD_FORMAT, message: 'must contain digits, lower and upper case characters' },
            presence: true, length: { in: 6..15 }, confirmation: true, if: -> { password.present? }

  validates :email, uniqueness: true, presence: true,
  format: { with: URI::MailTo::EMAIL_REGEXP }
  validates :phone_number,:presence => true,on: %i[update],
            :numericality => true, uniqueness: true,
            :length => { :minimum => 10, :maximum => 15 }

  def add_friend(person)
    return false if (person_id = person.id) == id || friends.exists?(person_id)

    friends << person
  end
  # validates_associated :friends
  private

end

app/controllers/v1/expenses_controller.rb
# frozen_string_literal: true

module V1
  class ExpensesController < ApplicationController
    before_action :set_expense, only: %i[show]

    def index
      render expenses: @expenses
    end
    def show
      render expense: @expense
    end

    def new
      @expense = Expense.new
    end

    def create
      @expense = Group.find_by(id: params[:group_id]).expenses.new(expense_params)
      if @expense.save
        flash[:success] = 'Expense was added'
        redirect_to @expense
      end
    end

    private

    # attr_accessor :expenses
    def set_expense
      @expense = Group.find_by(id: params[:id])
    end

    def expense_params
      params.require(:expense).permit(:title, :total, :date_time, :description).to_h.symbolize_keys
    end
  end
end

app/controllers/v1/friends_controller.rb
# frozen_string_literal: true
module V1
  class FriendsController < ApplicationController
    before_action :set_friend, only: %i[show destroy]
    def index
      @friends = current_user.friends
      render friends: @friends
    end

    def show
      authorize @friend, policy_class: FriendPolicy
    end

    def new
      @friend =
        if search_params[:email].present?
          User.where("email LIKE ?", "%" + search_params[:email] + "%").first || 'User not found, please check is email correct'
        else
          nil
        end
      render friend: @friend
    end

    def add
      @friend = User.find_by(id: user_params[:id])
      if current_user.add_friend(@friend)
        flash[:notice] = 'Friend was added'
        render :new, friend: @friend = nil
      else
        flash[:alert] = 'Friend is already added'
        render :new, friend: @friend = nil
      end
    end

    def destroy
      current_user.friends.delete(@friend)
      flash[:notice] = 'Friend was deleted'
      render :index
    end

    private

    def search_params
      params.fetch(:friend, {}).permit(:email)
    end

    def user_params
      params.require(:friend).permit(:id)
    end

    def set_friend
      @friend = User.find_by(id: params[:id])
    end
  end
end

app/controllers/v1/groups_controller.rb
# frozen_string_literal: true

module V1
  class GroupsController < ApplicationController
    before_action :set_group, only: %i[show new_expense]
    def index
      @groups = current_user.groups
      render groups: @groups
    end

    def show
      render group: @group
    end

    def new
      @group = Group.new
    end

    def create
      @group = current_user.own_groups.new(group_params)
      if @group.save
        flash[:success] =  'Group was created'
        redirect_to @group, notice: 'Group was created'
      end
    end

    def new_expense
      @expenseable = @group

    end

    private

    # attr_accessor :groups
    def set_group
      @group = Group.find_by(id: params[:id])
    end

    def group_params
      params.require(:group).permit(:name, :group_type).to_h.symbolize_keys
    end
  end
end

app/controllers/v1/sessions_controller.rb
# frozen_string_literal: true

module V1
  class SessionsController < ApplicationController
    def new

    end

    def create
      user = User.find_by( email: params[:email])
      if user.present? && user.authenticate(params[:password])
        session[:user_id] = user.id
        session[:email] = user.email
        flash[:success] = 'Logged in successfuly'
        redirect_to root_path#, notice: 'Logged in successfuly'
      else
        flash[:alert] = 'Invalid email or password'
        render :new
      end
    end
    def destroy
      session[:user_id] = nil
      session[:email] = nil
      redirect_to root_path, notice: 'Logged out'
    end
  end
end

app/controllers/v1/users_controller.rb
# frozen_string_literal: true

module V1
  class UsersController < ApplicationController
    def new
      @user = User.new
    end

    def create
      @user = User.new(sign_up_params.except(:confirm_password))
      if @user.save
        session[:user_id] = @user.id
        session[:email] = @user.email
        redirect_to root_path, notice: 'Successfully created account'
      else
        flash[:alert] = 'Something went wrong'
        render :new
      end
    end

    def show
      @user = current_user
    end

    def edit
      @user = current_user
    end
    def edit_password
      @user = current_user
    end

    def update
      if (@user = current_user).update(update_params)
        # flash[:success] = 'Ac/count data is successfully updated'
        redirect_to profile_path
      else
        flash[:alert] = 'Something went wrong'
        render :edit, user: @user
      end
    end

    def update_password
      if (@user = current_user).authenticate_password(password_params.except[:old_password])
        if @user.update(password_params.except(:old_password))
          flash[:success] = 'Account password is successfully updated'
          redirect_to profile_path#, notice: 'Account password is successfully updated '
        else
          flash[:alert] = 'Something went wrong'
          render :edit_password, user: @user
        end
      else
        @user.errors.add(:old_password, 'is incorrect')
        render :edit_password, user: @user
      end
    end

    def sign_up_params
      params.require(:user).permit(
        :email, :full_name, :phone_number, :password, :password_confirmation
      ).to_h.symbolize_keys
    end
    def update_params
      params.require(:user).permit(:email, :full_name, :phone_number).to_h.symbolize_keys
    end

    def password_params
      params.require(:user).permit(:old_password, :password, :password_confirmation).to_h.symbolize_keys
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/v1/users/edit.html.erb
<h1>Sign Up</h1>

<%= form_with model: @user,  url: profile_update_path  do |form| %>
  <% if @user.errors.any? %>
    <div class="alert alert-danger">
      <% @user.errors.full_messages.each do |message|%>
      <div> <%= message %></div>
      <%end %>
    </div>
    <%end %>
  <div class="row justify-content-start">
    <div class="col-2">
      <span for="InputEmail1" class="col-form-label">Email address</span>
    </div>
    <div class="col-3">
      <%= form.text_field :email, class: "form-control", id: "InputEmail1", 'aria-describedby': "emailHelp"%>
    </div>
    <div class="col-auto">
      <div id="emailHelp" class="form-text">We'll never share your email with anyone else.</div>
    </div>
  </div>
    <div class="row justify-content-start">
      <div class="col-2">
        <span for="InputFullName1" class="col-form-label">Full name</span>
      </div>
      <div class="col-3">
        <%= form.text_field :full_name, class: "form-control", id: "InputFullName1"%>
      </div>
    </div>
    <div class="row justify-content-start">
      <div class="col-2">
        <span for="InputPhoneNumber1" class="form-label">Phone number</span>
      </div>
      <div class="col-3">
        <%= form.phone_field :phone_number, class: "form-control", id: "InputPhoneNumber1"%>
      </div>
    </div>
  <button type="submit" class="btn btn-primary">Edit</button>
<% end %>

app/views/v1/users/edit_password.html.erb
<h1>Edit password</h1>

<%= form_with model: @user,  url: profile_update_password_path  do |form| %>
  <% if @user.errors.any? %>
    <div class="alert alert-danger">
      <% @user.errors.full_messages.each do |message|%>
      <div> <%= message %></div>
      <%end %>
    </div>
    <%end %>
  <div class="row justify-content-start">
    <div class="col-2">
      <span for="InputOldPassword1" class="col-form-label">Old password</span>
    </div>
    <div class="col-3">
      <%= form.password_field :old_password, class: "form-control", id: "InputOldPassword1", 'aria-describedby': "emailHelp"%>
    </div>
  </div>
    <div class="row justify-content-start">
      <div class="col-2">
        <span for="InputNewPassword1" class="col-form-label">New password</span>
      </div>
      <div class="col-3">
        <%= form.password_field :password, class: "form-control", id: "InputNewPassword1"%>
      </div>
    </div>
    <div class="row justify-content-start">
      <div class="col-2">
        <span for="InputConfirmPassword1" class="form-label">Confirm password</span>
      </div>
      <div class="col-3">
        <%= form.password_field :password_confirmation, class: "form-control", id: "InputConfirmPassword1"%>
      </div>
    </div>
  <button type="submit" class="btn btn-primary">Update</button>
<% end %>

app/views/v1/users/new.html.erb
<h1>Sign Up</h1>

<%= form_with model: @user,  url: sign_up_path  do |form| %>
  <% if @user.errors.any? %>
    <div class="alert alert-danger">
      <% @user.errors.full_messages.each do |message|%>
      <div> <%= message %></div>
      <%end %>
    </div>
    <%end %>
  <div class="row justify-content-start">
    <div class="col-2">
      <label for="InputEmail1" class="col-form-label">Email address</label>
    </div>
    <div class="col-3">
      <%= form.text_field :email, class: "form-control", id: "InputEmail1", 'aria-describedby': "emailHelp"%>
    </div>
    <div class="col-auto">
      <div id="emailHelp" class="form-text">We'll never share your email with anyone else.</div>
    </div>
  </div>
    <div class="row justify-content-start">
      <div class="col-2">
        <label for="InputFullName1" class="col-form-label">Full name</label>
      </div>
      <div class="col-3">
        <%= form.text_field :full_name, class: "form-control", id: "InputFullName1"%>
      </div>
    </div>
    <div class="row justify-content-start">
      <div class="col-2">
        <label for="InputPhoneNumber1" class="form-label">Phone number</label>
      </div>
      <div class="col-3">
        <%= form.phone_field :phone_number, class: "form-control", id: "InputPhoneNumber1"%>
      </div>
    </div>
    <div class="row justify-content-start">
      <div class="col-2">
        <label for="InputPassword1" class="form-label">Password</label>
      </div>
      <div class="col-3">
        <%= form.password_field :password, class: "form-control", id: "InputPassword1" %>
      </div>
    </div>
    <div class="row justify-content-start">
      <div class="col-2">
        <label for="InputConfirmPassword1" class="form-label">Confirm password</label>
      </div>
      <div class="col-3">
        <%= form.password_field :password_confirmation, class: "form-control", id: "InputConfirmPassword1" %>
      </div>
    </div>

  <button type="submit" class="btn btn-primary">Sign Up</button>
<% end %>

app/views/v1/users/show.html.erb
<h5 class="card-title ps-2">  <%= @user.full_name %></h5>
<div class="row p-1 text-decoration-none text-dark">
    <div class="col-6 col-sm-1">Email:</div>
    <div class="col-6 col-sm-2"><%= @user.email %></div>
</div>
<div class="row p-1 text-decoration-none text-dark">
  <div class="col-6 col-sm-1">Phone number:</div>
  <div class="col-6 col-sm-2"><%= @user.phone_number %></div>
</div>
<div class="row p-1 text-decoration-none text-dark">
  <div class="col-6 col-sm-1">
    <a href=<%= profile_edit_path %>>
      <button type="button" class="btn btn-primary">Edit profile</button>
    </a>
  </div>
  <div class="col-6 col-sm-2">
    <a href=<%= profile_edit_password_path %>>
      <button type="button" class="btn btn-primary">Update password</button>
    </a>
  </div>
</div>