config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  scope module: :v1 do
    get :sign_up, to: 'users#new'
    post :sign_up, to: 'users#create'
    get :sign_in, to: 'sessions#new'
    post :sign_in, to: 'sessions#create'
    get :profile, to: 'users#show'
    get 'profile/edit', to: 'users#edit'
    patch 'profile/update', to: 'users#update'
    get 'profile/edit_password', to: 'users#edit_password'
    patch 'profile/update_password', to: 'users#update_password'
    delete :logout, to: 'sessions#destroy'
    resources :groups do
      resources :expenses, only: %i[create new] #do
      #     get :new
      #     post :new, to: 'groups#create'
      # end
    end
    post 'groups/new', to: 'groups#create'
    resources :friends, only: %i[index show new add destroy]
    post 'friends/add', to: 'friends#add'
  end

  root to: 'status#check'
end

app/controllers/v1/expenses_controller.rb
# frozen_string_literal: true

module V1
  class ExpensesController < ApplicationController
    before_action :set_expense, only: %i[show]

    def index
      render expenses: @expenses
    end
    def show
      render expense: @expense
    end

    def new
      @expense = Expense.new
    end

    def create
      @expense = Group.find_by(id: params[:group_id]).expenses.new(expense_params)
      if @expense.save
        flash[:success] = 'Expense was added'
        redirect_to @expense
      end
    end

    private

    # attr_accessor :expenses
    def set_expense
      @expense = Group.find_by(id: params[:id])
    end

    def expense_params
      params.require(:expense).permit(:title, :total, :date_time, :description).to_h.symbolize_keys
    end
  end
end

app/controllers/v1/friends_controller.rb
# frozen_string_literal: true
module V1
  class FriendsController < ApplicationController
    before_action :set_friend, only: %i[show destroy]
    def index
      @friends = current_user.friends
      render friends: @friends
    end

    def show
      authorize @friend, policy_class: FriendPolicy
    end

    def new
      @friend =
        if search_params[:email].present?
          User.where("email LIKE ?", "%" + search_params[:email] + "%").first || 'User not found, please check is email correct'
        else
          nil
        end
      render friend: @friend
    end

    def add
      @friend = User.find_by(id: user_params[:id])
      if current_user.add_friend(@friend)
        flash[:notice] = 'Friend was added'
        render :new, friend: @friend = nil
      else
        flash[:alert] = 'Friend is already added'
        render :new, friend: @friend = nil
      end
    end

    def destroy
      current_user.friends.delete(@friend)
      flash[:notice] = 'Friend was deleted'
      render :index
    end

    private

    def search_params
      params.fetch(:friend, {}).permit(:email)
    end

    def user_params
      params.require(:friend).permit(:id)
    end

    def set_friend
      @friend = User.find_by(id: params[:id])
    end
  end
end

app/controllers/v1/groups_controller.rb
# frozen_string_literal: true

module V1
  class GroupsController < ApplicationController
    before_action :set_group, only: %i[show new_expense]
    def index
      @groups = current_user.groups
      render groups: @groups
    end

    def show
      render group: @group
    end

    def new
      @group = Group.new
    end

    def create
      @group = current_user.own_groups.new(group_params)
      if @group.save
        flash[:success] =  'Group was created'
        redirect_to @group, notice: 'Group was created'
      end
    end

    def new_expense
      @expenseable = @group

    end

    private

    # attr_accessor :groups
    def set_group
      @group = Group.find_by(id: params[:id])
    end

    def group_params
      params.require(:group).permit(:name, :group_type).to_h.symbolize_keys
    end
  end
end

app/controllers/v1/sessions_controller.rb
# frozen_string_literal: true

module V1
  class SessionsController < ApplicationController
    def new

    end

    def create
      user = User.find_by( email: params[:email])
      if user.present? && user.authenticate(params[:password])
        session[:user_id] = user.id
        session[:email] = user.email
        flash[:success] = 'Logged in successfuly'
        redirect_to root_path#, notice: 'Logged in successfuly'
      else
        flash[:alert] = 'Invalid email or password'
        render :new
      end
    end
    def destroy
      session[:user_id] = nil
      session[:email] = nil
      redirect_to root_path, notice: 'Logged out'
    end
  end
end

app/controllers/v1/users_controller.rb
# frozen_string_literal: true

module V1
  class UsersController < ApplicationController
    def new
      @user = User.new
    end

    def create
      @user = User.new(sign_up_params.except(:confirm_password))
      if @user.save
        session[:user_id] = @user.id
        session[:email] = @user.email
        redirect_to root_path, notice: 'Successfully created account'
      else
        flash[:alert] = 'Something went wrong'
        render :new
      end
    end

    def show
      @user = current_user
    end

    def edit
      @user = current_user
    end
    def edit_password
      @user = current_user
    end

    def update
      if (@user = current_user).update(update_params)
        # flash[:success] = 'Ac/count data is successfully updated'
        redirect_to profile_path
      else
        flash[:alert] = 'Something went wrong'
        render :edit, user: @user
      end
    end

    def update_password
      if (@user = current_user).authenticate_password(password_params.except[:old_password])
        if @user.update(password_params.except(:old_password))
          flash[:success] = 'Account password is successfully updated'
          redirect_to profile_path#, notice: 'Account password is successfully updated '
        else
          flash[:alert] = 'Something went wrong'
          render :edit_password, user: @user
        end
      else
        @user.errors.add(:old_password, 'is incorrect')
        render :edit_password, user: @user
      end
    end

    def sign_up_params
      params.require(:user).permit(
        :email, :full_name, :phone_number, :password, :password_confirmation
      ).to_h.symbolize_keys
    end
    def update_params
      params.require(:user).permit(:email, :full_name, :phone_number).to_h.symbolize_keys
    end

    def password_params
      params.require(:user).permit(:old_password, :password, :password_confirmation).to_h.symbolize_keys
    end
  end
end

app/views/v1/friends/index.html.erb
<% if @friends.present? %>
  <% @friends.each do |friend| %>
    <div class="w-100">
      <a class="row p-1 text-decoration-none text-dark" href= <%= friend_path(friend) %>>
        <div class="col-6 col-sm-1"><%=friend.full_name %></div>
        <div class="col-6 col-sm-1"><%=friend.email %></div>
      </a>
    </div>

  <% end %>
<% else %>
  <div>
    <h6 class="card-title ps-2">No friends</h6>
  </div>
<% end %>


<div>
  <a href=<%=new_friend_path%>>
    <button type="button" class="btn btn-primary">Find friend</button>
  </a>
</div>

app/views/v1/friends/new.html.erb
<%= form_tag(new_friend_path, method: :get) do %>
  <%= text_field_tag('friend[email]')%>
  <%= submit_tag "Search" %>
<% end %>
<% if @friend.is_a?(String)%>
  <h6 class="card-title ps-2"> <%= @friend %></h6>
<% elsif @friend.present?%>
    <div class="w-100">
      <a class="row p-1 text-decoration-none text-dark" href="http://www.google.com">
        <div class="col-6 col-sm-1"><%=@friend.full_name %></div>
        <div class="col-6 col-sm-1"><%= @friend.email %></div>
        <div class="col-6 col-sm-1">
<!--          <a href=<%#= friends_add_path %>, role="button">-->
<!--            <button type="button" class="btn btn-primary">Add friend</button>-->
            <%= button_to 'Add friend', friends_add_path, params: { friend: { id: @friend.id }} %>
<!--          </a>-->
        </div>
      </a>
    </div>
<% end %>

app/views/v1/friends/show.html.erb
<h5 class="card-title ps-2">  <%= @friend.full_name %></h5><div class="d-flex flex-column align-items-center">
  <div class="w-100">
    <div class="col-6 col-sm-1"><%=@friend.full_name %></div>
    <div class="col-6 col-sm-1"><%= @friend.email %></div>
  </div>
</div>
<div>
  <%= button_to 'Delete', friend_path(@friend), method: :delete %>
</div>