config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  scope module: :v1 do
    get :sign_up, to: 'users#new'
    post :sign_up, to: 'users#create'
    get :sign_in, to: 'sessions#new'
    post :sign_in, to: 'sessions#create'
    get :profile, to: 'users#show'
    get 'profile/edit', to: 'users#edit'
    patch 'profile/update', to: 'users#update'
    get 'profile/edit_password', to: 'users#edit_password'
    patch 'profile/update_password', to: 'users#update_password'
    delete :logout, to: 'sessions#destroy'
    resources :groups do
      resources :expenses, only: %i[create new] #do
      #     get :new
      #     post :new, to: 'groups#create'
      # end
    end
    post 'groups/new', to: 'groups#create'
    resources :friends, only: %i[index show new add destroy]
    post 'friends/add', to: 'friends#add'
  end

  root to: 'status#check'
end

app/views/layouts/_footer.html.erb
<div> I'm footer </div>

app/views/layouts/_header.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_pack_tag %>
</head>

<body>
<nav class="navbar navbar-expand-lg bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="/">Main</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="/groups">Groups</a>
        </li>
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href=<%= friends_path %>>Friends</a>
        </li>


        <% if session[:email]%>
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="/profile"><%="Logged in as: #{session[:email]}" %> </a>
          </li>
          <li class="nav-item">
<!--            <a class="nav-link active" aria-current="page" data-method="delete" href=<%#= logout_path %>>Logout</a>-->
            <%=  button_to 'logout', logout_path, method:"delete", class:"nav-link active", id:"pills-home-tab", 'data-bs-toggle':"pill", type:"button", role:"tab", 'aria-controls':"pills-home", 'aria-selected':"true" %>
<!--            class:"nav-link active", 'aria-current':"page",-->
          </li>
        <% else %>
          <li class="nav-item">
            <a class="nav-link active" aria-="page" href="/sign_up">Sign Up</a>
          </li>
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="/sign_in">Sign In</a>
          </li>
        <% end %>

      </ul>
    </div>
  </div>
</nav>
<!--<ul>-->
<!--  <li> <a class="nav" href="/"> Main page </a> </li>-->
  <%# if session[:email]%>
<!--    <div> <%#= "Logged in as: #{session[:email]}" %> </div>-->
  <%# else %>
<!--    <li> <a class="nav" href="/sign_up"> Sign Up </a> </li>-->
<!--    <li> <a class="nav" href="/sign_in"> Sign In </a> </li>-->
<%# end %>
<!--</ul>-->
</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BabloSpliter</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <% flash.each do |type,msg| %>
    <div class="alert alert-info">
      <%= msg %>
    </div>
    <% end %>
    <%= yield %>
    <%= render 'layouts/footer' %>
  </body>
</html>